# Generated by Django 3.2.5 on 2021-08-01 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0005_auto_20210801_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210801_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='portfolio.business')),
                ('field_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='user.field')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
