# Generated by Django 3.2.6 on 2021-08-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('average', '0002_auto_20210801_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Average',
        ),
    ]
