# Generated by Django 3.2.5 on 2021-08-01 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('post_attachment', models.FileField(blank=True, null=True, upload_to='image/')),
                ('post_date', models.DateTimeField()),
                ('com_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='community.category')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_comment', models.CharField(max_length=100)),
                ('cm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmcomment', to='community.community')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmcomment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
