# Generated by Django 3.0.6 on 2021-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_title', models.CharField(max_length=200)),
                ('pf_content', models.TextField()),
                ('pf_attach', models.FileField(blank=True, null=True, upload_to='images/')),
                ('pf_date', models.DateTimeField()),
            ],
        ),
    ]
